// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://quchhqfsgdsmblmxtbjs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1Y2hocWZzZ2RzbWJsbXh0YmpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDAyNTMzMjEsImV4cCI6MjA1NTgyOTMyMX0.nQk9xmaT_06ySx1YnNyqWmxD3wpPA5Cm2Mo3YylWVP8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);